on:
  push:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4.1.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: arn:aws:iam::410793108087:role/github-actions-terraform

      - name: Run terraform init
        run: terraform init

      - name: Run terraform plan
        run: terraform plan
      
      - name: Run terraform apply
        run: terraform apply -auto-approve